#!/bin/bash 

#    Copyright 2020-2021 Renzo Davoli
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Debian Official Cloud Images (SID)
BASEDIR=http://cdimage.debian.org/cdimage/cloud/sid/daily/

# get the tag of the latest image
LATESTTAG=$(wget -q -O - $BASEDIR | \
		grep -o '<a .*href=.*>' | grep -E '2[0-9]{7}-[0-9]{3}' | sed -e 's/<a /\n<a /g' | tail -1 | \
		sed -e 's/<a .*href=['"'"'"]//' -e 's/["'"'"'].*$//' -e 's/\/$//' -e '/^$/ d')

IMAGETAG=debian-sid-nocloud-amd64-daily-
V2TAG=debian-sid-v2-amd64-daily-

# local name of the image
PATHIMG=${IMAGETAG}${LATESTTAG}.qcow2
# url of the image
URLIMG=${BASEDIR}${LATESTTAG}/${PATHIMG}
# local name of the image in raw format (needed to exmpand the root partition)
PATHRAW=${IMAGETAG}${LATESTTAG}.img
# local name of the V2 image
PATHV2=${V2TAG}${LATESTTAG}.qcow2
# hostname 
HOSTNAME=V2-${LATESTTAG}
# URL install_packets_for_v2
V2PACK="https://raw.githubusercontent.com/virtualsquare/virtualsquare.github.io/master/archive/install_scripts/install_packets_for_v2.sh"
# URL install_v2_projects
V2PROJ="https://raw.githubusercontent.com/virtualsquare/virtualsquare.github.io/master/archive/install_scripts/install_v2_projects.sh"

# do not download the image twice if it is already here
if [ ! -f $PATHIMG ]
then
	wget $URLIMG
fi

# convert to raw
qemu-img convert -f qcow2 -O raw $PATHIMG $PATHRAW
# enlarge the disk image file to 10G
truncate --size=10G $PATHRAW
# trick to update the GPT header
printf "fix\n" | /sbin/parted ---pretend-input-tty $PATHRAW print
# resize the root partition
/sbin/parted -s $PATHRAW resizepart 1 100%
# print the new partition table
/sbin/parted -s $PATHRAW print
# convert the raw image to the V2 qcow2
qemu-img convert -f raw -O qcow2 $PATHRAW $PATHV2

# remove the temporary raw image
rm -f $PATHRAW

# set hostmame, update/install xterm and xauth, set root passowrd 
#	    get the v2 scripts
#     set the exec bit for scripts
#     generate ssh host keys
#     allow ssh passwd authehtication for users and root
#     create the virtualsquare user and set its password
#     set a fancy prompt for capabilities and vuos environments
virt-sysprep -a $PATHV2 \
		--hostname $HOSTNAME \
		--root-password password:virtualsquare \
		--network \
		--update --install xterm,xauth,adduser \
		--run-command 'echo "#!/bin/bash" > /root/get_v2all' \
		--run-command "echo wget $V2PACK >> /root/get_v2all" \
		--run-command "echo wget $V2PROJ >> /root/get_v2all" \
		--run-command 'echo "chmod +x /root/install_packets_for_v2.sh /root/install_v2_projects.sh" >> /root/get_v2all' \
		--run-command 'echo "/root/install_packets_for_v2.sh && /root/install_v2_projects.sh" >> /root/get_v2all' \
		--run-command 'chmod +x /root/get_v2all' \
		--run-command 'apt install --yes wget ssh' \
		--run-command 'cd /root; wget https://raw.githubusercontent.com/virtualsquare/virtualsquare.github.io/master/archive/install_scripts/append_to.bashrc' \
		--run-command 'cd /etc/profile.d; wget https://raw.githubusercontent.com/virtualsquare/virtualsquare.github.io/master/archive/install_scripts/local_lib.sh' \
		--run-command 'ssh-keygen -A' \
		--run-command "sed -i 's/^.*PasswordAuthentication.*$/#PasswordAuthentication yes/' /etc/ssh/sshd_config" \
		--run-command "sed -i 's/^.*PermitRootLogin.*$/PermitRootLogin Yes/' /etc/ssh/sshd_config" \
		--run-command 'adduser --disabled-password --gecos "" user' \
		--run-command 'echo "user:virtualsquare" | chpasswd' \
		--run-command 'cat /root/append_to.bashrc >> /home/user/.bashrc'
